// reporter.js
// Sends all audit results to Claude and gets back a clean markdown report.

const Anthropic = require('@anthropic-ai/sdk');

const client = new Anthropic();
// ANTHROPIC_API_KEY is read automatically from the environment / .env file

function formatResults(results) {
  return results
    .map(r => `[${r.status.toUpperCase().padEnd(4)}] ${r.check}: ${r.message}`)
    .join('\n');
}

async function generateReport(url, seoResults, conversionResults) {
  const auditDate  = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const seoText    = formatResults(seoResults);
  const convText   = formatResults(conversionResults);

  // ── System prompt (cached — billed only once per session) ─────────────────
  const systemPrompt = `You are a senior SEO consultant and conversion rate optimizer at a marketing agency.
You write audit reports for business owners who are NOT technical.
Your tone is friendly, direct, and helpful — like a trusted advisor, not a robot.
You only use the audit data you are given. You never invent data or make assumptions beyond what is provided.
When you see a FAIL, explain why it matters in plain English.
When you see a PASS, briefly acknowledge it.
Scores are calculated honestly: every FAIL = −10 points, every WARN = −5 points, starting from 100.`;

  // ── User prompt ────────────────────────────────────────────────────────────
  const userPrompt = `I just ran an automated audit on this website: ${url}

Here are the raw results:

=== SEO CHECKS ===
${seoText}

=== CONVERSION & MESSAGING CHECKS ===
${convText}

Please write a complete audit report in Markdown using EXACTLY this structure:

---

# Website Audit Report
**URL:** ${url}
**Date:** ${auditDate}

---

## Overall Scores

| Category | Score | Rating |
|----------|-------|--------|
| SEO | [calculate]/100 | [Poor / Needs Work / Good] |
| Conversion | [calculate]/100 | [Poor / Needs Work / Good] |
| Messaging | [calculate based on clarity checks]/100 | [Poor / Needs Work / Good] |

> Scoring: start at 100. Each FAIL = −10 pts, each WARN = −5 pts.
> 0–49 = Poor | 50–74 = Needs Work | 75–100 = Good

---

## SEO Issues

[List every FAIL and WARN from the SEO checks as bullet points. Explain each one in 1–2 plain-English sentences. Why does it matter? What will happen if they ignore it?]

---

## Conversion Gaps

[List every FAIL and WARN from the conversion checks. Focus on what is missing and how it costs them leads or sales.]

---

## Messaging Issues

[Based on the value proposition, audience, and next-step checks — is it clear what they do, who they help, and what the visitor should do next? Write 2–4 bullet points.]

---

## Priority Fixes (Top 5)

Ranked by impact — fix these first:

1. **[Fix name]** — [1–2 sentences on what to do and why it matters most]
2. **[Fix name]** — [same]
3. **[Fix name]** — [same]
4. **[Fix name]** — [same]
5. **[Fix name]** — [same]

---

## What's Working

[List 2–4 things that passed. Keep it brief and positive.]

---

*Report generated by SEO Audit Tool — Marketing Agency Edition*`;

  // ── Call Claude ────────────────────────────────────────────────────────────
  const response = await client.messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 2048,
    system: [
      {
        type: 'text',
        text: systemPrompt,
        cache_control: { type: 'ephemeral' }, // prompt caching — saves cost on repeat audits
      },
    ],
    messages: [
      { role: 'user', content: userPrompt },
    ],
  });

  return response.content[0].text;
}

module.exports = { generateReport };
